export const sections = [
  `Attacking: Attacks are any method of punching, blasting, or slashing your opponent’s character, which will cause their damage percent to go up. Attacking not only helps you to raise your opponents damage percent (making them easier to knock off the screen), but it can also finish them off, stun them, trip them, or otherwise make life harder on your opponent.However, there are a variety of different ways to attack in this game.`,
  `Neutral Attacks: These are your normal attacks. Each fighter has a different normal attack for standing without pressing any other button but(X).Some fighters can repeatedly press or hold(X) to perform “jab combos”, or a string of different attacks that follow one another without pressing different buttons.`,
  `Crouching Attacks: These attacks are performed by pressing(X) while holding down on the(movement stick).`,
  `Tilt Attacks: These attacks are performed while on the ground by lightly pressing and holding a directional button(left, right, down or up) and attacking.`,
  `Smash Attacks: These attacks are performed while on the ground by pressing a directional button and holding the attack button.`,
  `Aerial Attacks: These attacks are performed by pressing(X) while not on the ground.There are Neutral Air Attacks as well as Directional Air Attacks.`,
  `Dash Attacks: These attacks can only be performed by pressing(X) while a character is on the ground running.`,
  `Grabs: Grabs can be performed by getting close to an enemy and pressing(Bumper).In this state, your opponent will be unable to move for a short period of time, and this time gets longer the more damage your opponent has taken.You can also press(Bumper) or(X) to attack your opponent while they are stuck in this way.`,
  `Throws: Throws can be performed only while your opponent is grabbed by pressing(X) in conjunction with a directional input to throw them in a specific direction and deal damage.`,
  `Get - Up Attacks: This attack can be performed while on the ground, hanging on a ledge, or after having been knocked down by pressing the(X) button.`,
  `Special Moves: Each character has special moves that have interesting and highly varied properties relating to the games they originated from.These attacks can be performed by pressing(B) while either: using no directional inputs, holding left or right, holding down, or holding up.`,
  `Final Smash: These extremely powerful finishing moves can only be performed if you have broken a smash ball, or have filled up your final smash meter.You will be able to tell if you can use your final smash if your character is surrounded by bright light and the rest of the screen is darker than normal.To use a final smash, simply press(B) when you are surrounded by energy.There are many different final smashes with wildly different effects.Be sure to mess around with them and see what works!`
]
